import json
from datetime import datetime
from typing import Iterable
import sqlite3

FOODHUB_SEED = [
    {
        "category_id": 2,
        "sort_order": 1,
        "name": "Creamy carbonara",
        "tagline": "Silky, savoury, and fast.",
        "time_prep_min": 5,
        "time_cook_min": 20,
        "time_total_min": 25,
        "link": "https://www.bbcgoodfood.com/recipes/learn-to-make-spaghetti-carbonara",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/04/Carbonara-79ea3d8.jpg",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "400g spaghetti",
            "1 tbsp olive oil",
            "200g smoked pancetta, cubes (or streaky bacon, chopped)",
            "2 garlic cloves, crushed",
            "3 eggs",
            "75ml double cream",
            "50g Grana padano or parmesan, finely grated, plus extra to serve",
        ],
        "steps": [
            "Bring a large pan of salted water to the boil. Cook spaghetti to packet time, checking 1–2 minutes early for al dente.",
            "While pasta cooks, heat oil in a frying pan. Fry pancetta over medium heat until fat renders and it’s lightly golden, then take off the heat.",
            "In a bowl, beat 2 whole eggs plus 1 extra yolk with the cream, cheese, and seasoning.",
            "Add garlic to the pancetta and return the pan to high heat for about 1 minute to cook the garlic.",
            "Drain pasta and return to the hot pan off the heat. Pour in the egg mix and pancetta (with any fat), then toss quickly until creamy. Serve with extra cheese and pepper.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 2,
        "name": "Chilli con carne",
        "tagline": "Big flavour, comforting, and batchable.",
        "time_prep_min": 10,
        "time_cook_min": 60,
        "time_total_min": 70,
        "link": "https://www.bbcgoodfood.com/recipes/chilli-con-carne-recipe",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chilli-con-carne-a53a7ef.jpg",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "1 large onion",
            "1 red pepper",
            "2 garlic cloves",
            "1 tbsp oil",
            "1 heaped tsp hot chilli powder (or 1 level tbsp mild)",
            "1 tsp paprika",
            "1 tsp ground cumin",
            "500g lean minced beef",
            "1 beef stock cube",
            "400g can chopped tomatoes",
            "1/2 tsp dried marjoram",
            "1 tsp sugar",
            "2 tbsp tomato puree",
            "410g can red kidney beans",
            "plain boiled long grain rice, to serve",
            "soured cream, to serve",
        ],
        "steps": [
            "Dice onion, chop pepper, and finely chop garlic.",
            "Heat oil in a pan over medium heat. Cook onion for about 5 minutes until softened.",
            "Add garlic, pepper, chilli powder, paprika, and cumin. Cook 5 minutes, stirring occasionally.",
            "Increase heat, add mince, and cook at least 5 minutes, breaking it up until browned.",
            "Dissolve stock cube in 300ml hot water. Add to the pan with tomatoes, marjoram, sugar, tomato puree, and seasoning. Bring to the boil, cover, and simmer 20 minutes, stirring now and then.",
            "Stir in drained beans, bring back to the boil, then simmer uncovered for 10 minutes.",
            "Taste and season, then rest off the heat for 10 minutes. Serve with rice and soured cream.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 3,
        "name": "Gnocchi with creamy tomato & spinach sauce",
        "tagline": "Soft gnocchi, creamy tomato, quick finish.",
        "time_prep_min": 10,
        "time_cook_min": 10,
        "time_total_min": 20,
        "link": "https://www.bbcgoodfood.com/recipes/gnocchi-creamy-tomato-spinach-sauce",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/gnocchi-with-creamy-tomato-spinach-sauce-983b9a2.jpg",
        "tags": ["VEGETARIAN", "SAUCY"],
        "ingredients": [
            "1 tbsp olive oil",
            "2 garlic cloves, crushed",
            "400g can chopped tomato",
            "140g mascarpone",
            "500g pack gnocchi",
            "200g bag baby spinach",
            "handful basil leaves",
            "parmesan (or vegetarian alternative) shavings, to serve (optional)",
        ],
        "steps": [
            "Heat oil in a frying pan. Fry garlic until golden, add tomatoes, season, and simmer 10 minutes.",
            "Stir in mascarpone and cook for 2 minutes.",
            "Boil gnocchi to packet instructions, adding spinach for the final minute to wilt. Drain well.",
            "Return gnocchi and spinach to the pan, stir through the sauce, and serve with basil and parmesan if using.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 4,
        "name": "Chicken fried rice",
        "tagline": "Fast, punchy, and great for leftover rice.",
        "time_prep_min": 5,
        "time_cook_min": 10,
        "time_total_min": 15,
        "link": "https://www.bbcgoodfood.com/recipes/chicken-sweetcorn-egg-fried-rice",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chicken-sweetcorn-egg-fried-rice-9992c81.jpg",
        "tags": ["PROTEIN", "PANTRY"],
        "ingredients": [
            "1 tbsp sunflower oil",
            "3 eggs, beaten with some seasoning",
            "320g pack mixed stir-fry vegetable",
            "1 tbsp mild curry powder",
            "140g frozen sweetcorn",
            "600g cooked rice",
            "1 roasted chicken breast, finely shredded",
            "2 tbsp low-salt soy sauce",
            "2 tbsp sweet chilli sauce",
            "2 tbsp ketchup",
        ],
        "steps": [
            "Heat a splash of oil in a large frying pan. Add eggs, swirl into a thin layer, cook until set, then roll and slice. Set aside.",
            "Add a little more oil. Cook stir-fry veg with curry powder and sweetcorn plus a splash of water for 1–2 minutes, then tip into a bowl.",
            "Add remaining oil. Stir-fry rice and chicken, then add soy, sweet chilli, ketchup, a splash of water, and pepper.",
            "Return veg and sliced egg to the pan, toss, and heat through. Serve immediately.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 5,
        "name": "Tuna pasta",
        "tagline": "Zesty, light, and pantry-friendly.",
        "time_prep_min": 0,
        "time_cook_min": 25,
        "time_total_min": 25,
        "link": "https://www.bbcgoodfood.com/recipes/tuna-lemon-pasta",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tuna-lemon-pasta-0e6c602.jpg",
        "tags": ["SEAFOOD", "SAUCY"],
        "ingredients": [
            "350g pasta shells",
            "200g pack trimmed fine beans, cut into short lengths",
            "200g can tuna in oil",
            "1 lemon, zested",
            "1 heaped tbsp small capers",
            "generous pinch of chilli flakes",
            "olive oil, for drizzling",
        ],
        "steps": [
            "Boil pasta in salted water for 8 minutes. Add beans and cook for 3 minutes more until both are just tender.",
            "Flake tuna with its oil and mix with lemon zest, capers, chilli flakes, and seasoning.",
            "Drain pasta and beans, return to the pan, and toss through the tuna mix. Drizzle a little olive oil if needed.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 6,
        "name": "Sausage, kale & gnocchi one-pot",
        "tagline": "Hearty, comforting, and all in one pan.",
        "time_prep_min": 5,
        "time_cook_min": 15,
        "time_total_min": 20,
        "link": "https://www.bbcgoodfood.com/recipes/sausage-kale-gnocchi-one-pot",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/sausage-kale-gnocchi-one-pot-6ce457e.jpg",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "1 tbsp olive oil",
            "6 pork sausages",
            "1 tsp chilli flakes",
            "1 tsp fennel seeds (optional)",
            "500g fresh gnocchi",
            "500ml chicken stock (fresh if you can get it)",
            "100g chopped kale",
            "40g parmesan, finely grated",
        ],
        "steps": [
            "Heat oil in a large high-sided frying pan over medium heat. Squeeze sausagemeat from skins into the pan, add chilli flakes and fennel, and fry until crisp at the edges. Lift out with a slotted spoon.",
            "Add gnocchi and fry for about 1 minute. Pour in stock, cover, and cook for 3 minutes once bubbling.",
            "Stir in kale and cook 2 minutes more until gnocchi is tender and kale wilted.",
            "Stir in parmesan, season with pepper, and scatter sausage back over.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 7,
        "name": "Lemon dressed salmon with leek & broad bean puree",
        "tagline": "Bright salmon with a soft green base.",
        "time_prep_min": 10,
        "time_cook_min": 20,
        "time_total_min": 30,
        "link": "https://www.bbcgoodfood.com/recipes/lemon-dressed-salmon-leek-broad-bean-puree",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/lemon-dressed-salmon-leek-broad-bean-puree-3f6b720.jpg",
        "tags": ["SEAFOOD", "BRIGHT", "GREENS"],
        "ingredients": [
            "1/2 lemon, zested and juiced",
            "1 tbsp drained capers",
            "1 tbsp rapeseed oil, plus 1 tsp",
            "1 large leek (about 275g), sliced",
            "200g frozen baby broad beans",
            "2 skin-on wild salmon fillets",
            "250g bag spinach",
            "12 small basil leaves",
            "170g baby potatoes, boiled (halved if larger)",
        ],
        "steps": [
            "Mix lemon zest and juice with capers and 1 tbsp oil for the dressing.",
            "Boil leek and broad beans in salted water for 6–8 minutes until tender. Wilt spinach in the same water for 1–2 minutes.",
            "Heat 1 tsp oil in a non-stick pan. Fry salmon skin-side down for 4 minutes, flip, and cook 2–4 minutes until just done.",
            "Stir a couple spoonfuls of beans into the dressing. Blitz remaining beans and leek into a puree with a splash of cooking water if needed.",
            "Drain spinach, plate spinach with puree and salmon, spoon over dressing, scatter basil, and serve with potatoes.",
        ],
    },
    {
        "category_id": 2,
        "sort_order": 8,
        "name": "Vegetarian fajitas",
        "tagline": "Sizzling, bright, and easy to share.",
        "time_prep_min": 5,
        "time_cook_min": 10,
        "time_total_min": 15,
        "link": "https://www.bbcgoodfood.com/recipes/veggie-fajitas",
        "image_url": "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/veggie-fajitas-8bfe3b2.jpg",
        "tags": ["VEGETARIAN", "WRAP"],
        "ingredients": [
            "400g can black beans, drained",
            "small bunch coriander, finely chopped",
            "4 large or 8–12 small flour tortillas",
            "1 avocado, sliced (or 1 small tub guacamole)",
            "2 tbsp soured cream or creme fraiche",
            "1 red and 1 yellow pepper, cut into strips",
            "1 tbsp oil",
            "1 red onion, cut into thin wedges",
            "1 garlic clove, crushed",
            "1/2 tsp chilli powder",
            "1/2 tsp smoked paprika",
            "1/2 tsp ground cumin",
            "1 lime, juiced",
        ],
        "steps": [
            "Fry most of the pepper strips with onion in oil until softened and browned at the edges. Cool slightly, then mix in reserved raw pepper strips.",
            "Add garlic and cook for 1 minute. Add spices and cook a couple of minutes until aromatic. Add half the lime juice and seasoning; keep warm.",
            "Warm black beans with the remaining lime juice and seasoning, then stir through coriander.",
            "Warm tortillas, then serve with the fajita veg, beans, avocado, and soured cream.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 1,
        "name": "Sausage pasta",
        "tagline": "Saucy, hearty, and low-fuss.",
        "time_prep_min": 5,
        "time_cook_min": 25,
        "time_total_min": 30,
        "link": "https://www.bbcgoodfood.com/recipes/saucy-sausage-pasta-0",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "1 tbsp olive oil",
            "packet of 8 pork sausages (cut into chunky pieces)",
            "1 large onion (chopped)",
            "2 garlic cloves (crushed)",
            "1 tsp chilli powder",
            "400g can chopped tomatoes",
            "300g short pasta (e.g. fusilli/farfalle)",
        ],
        "steps": [
            "Put a large pan of water on to boil.",
            "Heat oil in a large frying pan. Fry sausage pieces on a fairly high heat until golden brown all over.",
            "Turn the heat down. Add onion and garlic; cook until softened.",
            "Stir in chilli powder and chopped tomatoes. Bring to the boil, then simmer so it bubbles for about 10 minutes while you cook the pasta.",
            "Cook pasta in boiling water to pack instructions.",
            "Drain pasta, tip into the sausage sauce, toss to coat, and serve.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 2,
        "name": "Easy mac and cheese",
        "tagline": "Baked, golden, and classic.",
        "time_prep_min": 15,
        "time_cook_min": 30,
        "time_total_min": 45,
        "link": "https://www.bbcgoodfood.com/recipes/macaroni-cheese-4-easy-steps",
        "tags": ["VEGETARIAN", "SAUCY"],
        "ingredients": [
            "700ml full-fat milk",
            "1 onion (peeled/halved)",
            "1 garlic clove (peeled)",
            "1 bay leaf",
            "350g macaroni",
            "50g butter (plus extra for greasing)",
            "50g plain flour",
            "175g cheddar (grated)",
            "1 tsp English mustard",
            "50g parmesan (grated)",
            "50g coarse white breadcrumb",
        ],
        "steps": [
            "Infuse milk: warm milk with onion, garlic, and bay leaf until almost boiling. Cover and leave 10 minutes, then strain.",
            "Cook macaroni until just soft but still with bite (about 10 minutes). Drain, rinse briefly, and stir to stop sticking.",
            "Heat oven to 190C / fan 170C / gas 5. Butter a 25x18cm ovenproof dish.",
            "Make a roux: melt butter, then add flour and cook 1 minute on low heat, stirring constantly.",
            "Slowly whisk in warm infused milk until smooth. Simmer 3–4 minutes, stirring often, until thick enough to coat a spoon. Off the heat, stir in cheddar and mustard; season and mix until melted.",
            "Mix sauce through macaroni and tip into the dish. Top with parmesan and breadcrumbs. Bake 15–20 minutes until bubbling and golden.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 3,
        "name": "Easy egg-fried rice",
        "tagline": "Fast and pantry-friendly.",
        "time_prep_min": 10,
        "time_cook_min": 10,
        "time_total_min": 20,
        "link": "https://www.bbcgoodfood.com/recipes/egg-fried-rice",
        "tags": ["VEGETARIAN", "PANTRY"],
        "ingredients": [
            "250g long grain rice",
            "3 tbsp vegetable oil",
            "1 onion (finely chopped)",
            "4 eggs (beaten)",
            "2 spring onions (sliced, to serve)",
        ],
        "steps": [
            "Cook rice to pack instructions, drain, spread out to steam-dry, and set aside.",
            "Heat 2 tbsp oil in a large wok on high heat. Fry onion until lightly browned, about 5 minutes.",
            "Add rice, stir and toast for about 3 minutes, then push to the side of the pan.",
            "Add remaining oil, then pour in beaten eggs.",
            "Let eggs cook a little, then mix into rice. Serve topped with spring onion.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 4,
        "name": "Tomato soup with cheese & Marmite toast",
        "tagline": "Cosy soup with a crunchy top.",
        "time_prep_min": 10,
        "time_cook_min": 15,
        "time_total_min": 25,
        "link": "https://www.bbcgoodfood.com/recipes/tomato-soup-cheese-marmite-toast",
        "tags": ["VEGETARIAN", "PANTRY"],
        "ingredients": [
            "1 tbsp olive oil",
            "1 medium onion (roughly chopped)",
            "1 tsp dried oregano",
            "1 garlic clove (chopped)",
            "1 small bunch basil (leaves picked)",
            "400g can plum tomatoes",
            "2 slices crusty bread (toasted)",
            "2 tsp Marmite",
            "50g parmesan (or vegetarian alternative), grated",
        ],
        "steps": [
            "Soup: heat oil in a saucepan on medium. Add onion and a big pinch of salt; cook until softened, about 5 minutes.",
            "Add oregano, garlic, and basil; cook 1 minute. Add plum tomatoes, half-fill the can with water and add that too. Simmer 10 minutes, then blitz smooth and season.",
            "Toast: heat grill to high. Spread toast with Marmite, top with parmesan, and grill 3–5 minutes until golden.",
            "Serve toast on top of soup with black pepper.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 5,
        "name": "Pesto pasta",
        "tagline": "The fastest option in the drawer.",
        "time_prep_min": 0,
        "time_cook_min": 5,
        "time_total_min": 5,
        "link": "https://www.bbcgoodfood.com/recipes/easy-pesto-pasta",
        "tags": ["VEGETARIAN", "PANTRY"],
        "ingredients": [
            "500g pack spaghetti (fresh or dried)",
            "2–3 tbsp pesto (from a jar)",
            "50g parmesan (or vegetarian alternative), shaved or grated",
        ],
        "steps": [
            "Boil spaghetti to pack instructions. Drain well and return to the pan.",
            "Toss with pesto and half the parmesan. Serve topped with remaining parmesan.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 6,
        "name": "Fish tacos",
        "tagline": "Bright, fresh, and satisfying.",
        "time_prep_min": 20,
        "time_cook_min": 10,
        "time_total_min": 30,
        "link": "https://www.bbcgoodfood.com/recipes/fish-tacos-2",
        "tags": ["SEAFOOD", "WRAP", "BRIGHT"],
        "ingredients": [
            "1 tsp ground cumin",
            "1 tsp ground coriander",
            "2 tsp smoked paprika",
            "2 limes",
            "500g white fish fillets (cod/haddock/pollack/tilapia, skin/bones removed)",
            "1/4 red cabbage",
            "2 large tomatoes",
            "2 large avocados",
            "2 tbsp vegetable oil",
            "8 small corn or wheat tortilla wraps",
            "small bunch coriander (chopped)",
            "1 green chilli (finely sliced, optional)",
            "100g soured cream",
            "chilli sauce (to serve)",
        ],
        "steps": [
            "Mix cumin, coriander, and paprika with a generous pinch of salt. Add juice of 1 lime to make a paste. Toss fish in the paste and set aside.",
            "Finely slice cabbage, squeeze over juice of 1/2 lime, season, and scrunch in. Chop tomatoes. Slice avocado (or mash with lime and salt).",
            "Heat grill to high. Line a tray with foil, brush with a little oil. Lay fish on the tray, scrape over any remaining paste, brush with a little more oil. Grill 8–10 minutes until cooked and starting to scorch.",
            "Warm tortillas. Assemble with soured cream, cabbage, tomatoes, avocado, flaked fish, coriander, chilli (optional), and chilli sauce.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 7,
        "name": "Shakshuka",
        "tagline": "Warm, spiced, and simple.",
        "time_prep_min": 5,
        "time_cook_min": 20,
        "time_total_min": 25,
        "link": "https://www.bbcgoodfood.com/recipes/shakshuka",
        "tags": ["VEGETARIAN", "PANTRY"],
        "ingredients": [
            "1 tbsp olive oil",
            "2 red onions (chopped)",
            "1 red chilli (deseeded and finely chopped)",
            "1 garlic clove (sliced)",
            "small bunch coriander (stalks and leaves chopped separately)",
            "2 cans cherry tomatoes",
            "1 tsp caster sugar",
            "4 eggs",
        ],
        "steps": [
            "Heat oil in a lidded frying pan. Soften onions, chilli, garlic, and coriander stalks for about 5 minutes until soft.",
            "Stir in tomatoes and sugar; bubble 8–10 minutes until thick.",
            "Make 4 little wells, crack an egg into each, and cover. Cook on low heat 6–8 minutes until eggs are done to your liking.",
            "Scatter coriander leaves and serve with crusty bread.",
        ],
    },
    {
        "category_id": 3,
        "sort_order": 8,
        "name": "Chickpea curry",
        "tagline": "Low effort, big payoff.",
        "time_prep_min": 15,
        "time_cook_min": 25,
        "time_total_min": 40,
        "link": "https://www.bbcgoodfood.com/recipes/kadala-curry",
        "tags": ["VEGETARIAN", "PANTRY", "SAUCY"],
        "ingredients": [
            "2 tbsp oil",
            "1 onion (diced)",
            "1 tsp fresh or dried chilli (to taste)",
            "9 garlic cloves",
            "thumb-sized piece ginger (peeled)",
            "1 tbsp ground coriander",
            "2 tbsp ground cumin",
            "1 tbsp garam masala",
            "2 tbsp tomato puree",
            "2 x 400g cans chickpeas (drained)",
            "400g can chopped tomatoes",
            "100g creamed coconut",
            "1/2 small pack coriander (chopped, plus extra to garnish)",
            "100g spinach",
            "cooked rice and/or dahl (to serve)",
        ],
        "steps": [
            "Paste start: heat a little of the oil in a frying pan; cook onion and chilli until softened, about 8 minutes.",
            "Blend: combine garlic, ginger, and remaining oil in a food processor, then add ground coriander, cumin, garam masala, tomato puree, 1/2 tsp salt, and the fried onion. Blend smooth.",
            "Cook paste: tip into a medium saucepan; cook 2 minutes on medium-high, stirring so it doesn't stick.",
            "Add chickpeas and tomatoes; simmer 5 minutes until reduced.",
            "Add creamed coconut and a little water; cook 5 minutes more. Add chopped coriander and spinach; cook until spinach wilts.",
            "Garnish with extra coriander; serve with rice or dahl.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 1,
        "name": "Roast sea bass & vegetable traybake",
        "tagline": "Bright, crisp, and herb-lifted.",
        "time_prep_min": 10,
        "time_cook_min": 30,
        "time_total_min": 40,
        "link": "https://www.bbcgoodfood.com/recipes/roast-sea-bass-vegetable-traybake",
        "tags": ["SEAFOOD", "BRIGHT", "GREENS"],
        "ingredients": [
            "300g red-skinned potatoes (thin rounds)",
            "1 red pepper (strips)",
            "2 tbsp extra virgin olive oil",
            "1 rosemary sprig (leaves finely chopped)",
            "2 sea bass fillets",
            "25g pitted black olives (halved)",
            "1/2 lemon (thin rounds)",
            "handful basil leaves",
        ],
        "steps": [
            "Heat oven to 180C/160C fan/gas 4. Toss potatoes and pepper with 1 tbsp oil, rosemary, salt and pepper on a large tray.",
            "Roast 25 minutes, turning halfway, until potatoes are crisp at the edges.",
            "Add sea bass on top, scatter olives, top fish with lemon slices, and drizzle remaining oil.",
            "Roast 7–8 minutes more until fish is cooked; finish with basil.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 2,
        "name": "Roast chicken traybake",
        "tagline": "Juicy chicken, roasted veg, minimal effort.",
        "time_prep_min": 10,
        "time_cook_min": 65,
        "time_total_min": 75,
        "link": "https://www.bbcgoodfood.com/recipes/roast-chicken-tray-bake",
        "tags": ["PROTEIN", "GREENS"],
        "ingredients": [
            "2 red onions (320g), sliced into rings",
            "1 large red pepper (3cm pieces)",
            "300g potatoes (3cm chunks)",
            "2 tbsp rapeseed oil",
            "4 bone-in chicken thighs (skin/fat removed)",
            "1 lime (zested + juiced)",
            "3 large garlic cloves (finely grated)",
            "1 tsp smoked paprika",
            "1 tsp thyme leaves",
            "2 tsp vegetable bouillon powder",
            "200g long stem broccoli (cut if thick)",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. Toss onion, pepper, and potatoes with oil in a roasting tin. Roast 15 minutes.",
            "Rub chicken thighs with lime zest, garlic, paprika, and thyme.",
            "Stir veg, then nestle chicken among it (covering with some onion). Roast 40 minutes.",
            "Mix 200ml boiling water with bouillon powder. Add broccoli to the tin, pour over hot stock and lime juice, cover with foil, and roast 10 minutes more until broccoli is just tender.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 3,
        "name": "Sausage traybake",
        "tagline": "Pesto, beans, and golden edges.",
        "time_prep_min": 10,
        "time_cook_min": 50,
        "time_total_min": 60,
        "link": "https://www.bbcgoodfood.com/recipes/pesto-sausage-traybake",
        "tags": ["PROTEIN", "GREENS"],
        "ingredients": [
            "1 red onion (wedges)",
            "4 new potatoes (thinly sliced)",
            "6 canned/jarred artichokes (halved)",
            "100g cherry tomatoes",
            "4 spring onions (halved lengthways)",
            "2 pork sausages (chunks)",
            "1 tsp fennel seeds",
            "1 small lemon (wedges)",
            "1/2 tbsp olive oil",
            "400g can flageolet or butter beans (drained/rinsed)",
            "150ml low-salt vegetable stock",
            "2 tbsp fresh pesto",
            "crusty bread (optional)",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 4. Toss onion, potatoes, artichokes, tomatoes, spring onions, sausage, fennel, and lemon in a tray; drizzle oil and season lightly.",
            "Roast 20 minutes.",
            "Add beans and stock; roast 35 minutes more.",
            "Swirl through pesto and serve.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 4,
        "name": "Halloumi traybake",
        "tagline": "Big tray, sizzling halloumi, soft veg.",
        "time_prep_min": 15,
        "time_cook_min": 60,
        "time_total_min": 75,
        "link": "https://www.bbcgoodfood.com/recipes/halloumi-traybake",
        "tags": ["VEGETARIAN", "GREENS"],
        "ingredients": [
            "750g baby new potatoes (halved)",
            "2 medium red onions (quartered/broken up)",
            "4 tbsp olive oil",
            "400g can chickpeas (drained)",
            "1 large red pepper (strips)",
            "1/2 romanesco broccoli or cauliflower (~400g florets)",
            "250g mixed colour cherry tomatoes",
            "4 garlic cloves (peeled)",
            "250g pack reduced fat halloumi (thinly sliced)",
            "small bunch basil (torn)",
        ],
        "steps": [
            "Heat oven to 160C/140C fan/gas 3. Put potatoes and onion in a large tin, pour over 2 tbsp oil; roast about 30 minutes.",
            "Add chickpeas, pepper, romanesco/cauli, tomatoes, and garlic; drizzle with 2 tbsp oil. Roast 20–25 minutes until cooked and browning.",
            "Put halloumi on top, then grill 5–10 minutes until melting and browned. Finish with basil.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 5,
        "name": "Honey mustard salmon traybake",
        "tagline": "Sweet-savoury glaze, tender salmon.",
        "time_prep_min": 15,
        "time_cook_min": 30,
        "time_total_min": 45,
        "link": "https://www.bbcgoodfood.com/recipes/honey-mustard-salmon-potato-and-tenderstem-traybake",
        "tags": ["SEAFOOD", "GREENS", "BRIGHT"],
        "ingredients": [
            "600g new potatoes (halved if large)",
            "400g long-stem broccoli",
            "2 tbsp wholegrain mustard",
            "2 tbsp honey",
            "2 tbsp rapeseed (or groundnut) oil",
            "4 skin-on salmon fillets (~120g each)",
        ],
        "steps": [
            "Boil potatoes in salted simmering water 10–15 minutes until tender; add broccoli for the last 2 minutes. Drain and steam-dry.",
            "Heat oven to 180C/160C fan/gas 4. Whisk honey, mustard, and 1 tbsp oil; season.",
            "Tip potatoes and broccoli onto a tray; drizzle remaining oil and toss. Add salmon skin-side down; brush with glaze.",
            "Roast 15–20 minutes until salmon flakes and potatoes are lightly golden.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 6,
        "name": "Spiced salmon & tomato traybake",
        "tagline": "Warm spice, saucy tomatoes.",
        "time_prep_min": 5,
        "time_cook_min": 25,
        "time_total_min": 30,
        "link": "https://www.bbcgoodfood.com/recipes/spiced-salmon-tomato-traybake",
        "tags": ["SEAFOOD", "SAUCY"],
        "ingredients": [
            "1 red onion (sliced)",
            "200g cherry tomatoes",
            "3 tbsp mild or madras curry paste",
            "400g can chickpeas (drained/rinsed)",
            "2 skinless salmon fillets",
            "1 large or 2 small naan breads",
            "2 tbsp fat-free yogurt",
            "lemon wedges and coriander leaves (optional)",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. Toss onion, tomatoes, 2 tbsp curry paste, chickpeas, and 200ml water in a deep 20x25cm tin; roast 15 minutes.",
            "Stir and season. Brush remaining curry paste over salmon; season. Nestle salmon into veg and roast 8–10 minutes until done.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 7,
        "name": "Puttanesca hake traybake",
        "tagline": "Briny, bold, and weeknight-friendly.",
        "time_prep_min": 10,
        "time_cook_min": 45,
        "time_total_min": 55,
        "link": "https://www.bbcgoodfood.com/recipes/puttanesca-hake-traybake",
        "tags": ["SEAFOOD", "SAUCY"],
        "ingredients": [
            "1 onion (sliced)",
            "500g baby potatoes (chunky coins)",
            "2 tbsp olive oil",
            "3 garlic cloves (bashed, skins on)",
            "400g can chopped tomatoes",
            "60g pitted olives (nocellara, sliced)",
            "1 tsp chilli flakes",
            "2 tbsp capers (drained, roughly chopped)",
            "3 anchovy fillets (finely chopped)",
            "4 hake fillets (~100g each)",
            "10g parsley (roughly chopped)",
        ],
        "steps": [
            "Heat oven to 220C/190C fan/gas 6. Put onion and potatoes in a roasting dish; drizzle oil, add garlic, season. Roast 25–30 minutes, turning halfway, until golden and cooked. Squeeze garlic from skins over potatoes.",
            "Season canned tomatoes. Scatter olives, chilli flakes, capers, and anchovies over potatoes; mix. Pour over tomatoes and nestle hake on top.",
            "Cover with foil and bake 10–15 minutes until fish is opaque and flakes easily.",
            "Scatter parsley and serve from the tray.",
        ],
    },
    {
        "category_id": 4,
        "sort_order": 8,
        "name": "Sweet potato, feta & butter bean traybake",
        "tagline": "Smoky, herby, and satisfying.",
        "time_prep_min": 15,
        "time_cook_min": 30,
        "time_total_min": 45,
        "link": "https://www.theguardian.com/food/2026/jan/05/quick-easy-roast-sweet-potato-recipe-feta-butter-bean-traybake-spring-onion-pesto-rukmini-iyer",
        "tags": ["VEGETARIAN", "HIGH FIBRE", "GREENS"],
        "ingredients": [
            "2 large sweet potatoes (1.5cm chunks)",
            "570g jar butter beans (or 400g tin), drained/rinsed",
            "2 tbsp olive oil",
            "2 tsp smoked paprika",
            "2 tsp flaky sea salt",
            "200g feta (crumbled)",
            "25g flat-leaf parsley",
            "3 spring onions",
            "50g almonds (or pine nuts)",
            "50ml extra-virgin olive oil",
            "juice of 1/2 lemon",
        ],
        "steps": [
            "Heat oven to 200C (180C fan)/gas 6. Toss sweet potato, butter beans, olive oil, smoked paprika, and 1 tsp of the salt in a tin; roast 30 minutes.",
            "Blitz pesto ingredients with 1/2 tsp salt; adjust lemon and salt; loosen with extra oil if you want thinner.",
            "Spoon pesto over the tray, scatter feta, and eat warm.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 1,
        "name": "Cottage pie",
        "tagline": "Big batch comfort.",
        "time_prep_min": 35,
        "time_cook_min": 110,
        "time_total_min": 145,
        "link": "https://www.bbcgoodfood.com/recipes/cottage-pie",
        "tags": ["PROTEIN", "PANTRY"],
        "ingredients": [
            "3 tbsp olive oil",
            "1 1/4kg beef mince",
            "2 onions (finely chopped)",
            "3 carrots (chopped)",
            "3 celery sticks (chopped)",
            "2 garlic cloves (finely chopped)",
            "3 tbsp plain flour",
            "1 tbsp tomato puree",
            "large glass red wine (optional)",
            "850ml beef stock",
            "4 tbsp Worcestershire sauce",
            "a few thyme sprigs",
            "2 bay leaves",
            "1.8kg potatoes (chopped)",
            "225ml milk",
            "25g butter",
            "200g strong cheddar (grated)",
            "freshly grated nutmeg",
        ],
        "steps": [
            "Brown mince: heat 1 tbsp oil and fry beef until browned in batches; set aside.",
            "Veg base: add remaining oil and cook onions, carrots, and celery gently about 20 minutes until soft.",
            "Add garlic, flour, and tomato puree; turn heat up and cook a few minutes, then return beef.",
            "Add wine (if using) and reduce slightly, then add stock, Worcestershire, thyme, and bay; stir.",
            "Simmer uncovered 45 minutes until thick. Discard bay and thyme stalks; season well.",
            "Mash: boil potatoes until tender, drain and steam-dry. Mash with milk, butter, and 3/4 of the cheese; season with nutmeg.",
            "Spoon filling into 2 dishes, top with mash, sprinkle remaining cheese.",
            "Bake at 220C/200C fan/gas 7 for 25–30 minutes until golden.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 2,
        "name": "Chicken & bacon pie",
        "tagline": "Flaky puff pastry, creamy filling.",
        "time_prep_min": 30,
        "time_cook_min": 60,
        "time_total_min": 60,
        "link": "https://www.bbcgoodfood.com/recipes/chicken-bacon-pie",
        "tags": ["PROTEIN"],
        "ingredients": [
            "1 tbsp flavourless oil",
            "500g chicken breasts (or boneless thighs), roughly chopped",
            "200g streaky bacon, roughly chopped",
            "1 onion, roughly chopped",
            "2 carrots, roughly chopped",
            "1 celery stick, finely chopped",
            "1 bay leaf",
            "a few thyme sprigs",
            "150ml white wine",
            "1 tbsp wholegrain mustard",
            "2 tbsp flour",
            "250ml chicken stock",
            "150ml double cream",
            "320g ready-rolled puff pastry",
            "1 egg, beaten",
            "peas or long-stem broccoli to serve (optional)",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. In a large lidded pan, heat oil and fry chicken and bacon until browned. Remove to a plate.",
            "Add onion, carrot, celery, bay, and thyme. Reduce heat, lid on, and cook 10–12 minutes until softened.",
            "Stir in wine and reduce 2–3 minutes. Add chicken and bacon back, stir in mustard, then flour; cook 1 minute.",
            "Pour in stock, season, bring to a simmer; stir in cream and bring back to a simmer.",
            "Turn off heat and pour filling into a ~23cm dish.",
            "Cover with puff pastry, trim and crimp, egg-wash, poke steam holes, and bake 30–40 minutes until golden.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 3,
        "name": "All-in-one roast chicken & veg",
        "tagline": "Tray roast, minimal fuss.",
        "time_prep_min": 10,
        "time_cook_min": 50,
        "time_total_min": 60,
        "link": "https://www.bbcgoodfood.com/recipes/all-one-roast-chicken-veg",
        "tags": ["PROTEIN", "GREENS"],
        "ingredients": [
            "8 baby new potatoes (halved)",
            "2 tsp olive oil",
            "2 carrots (sliced)",
            "1 courgette (sliced)",
            "1 leek (sliced)",
            "1 tsp each chopped thyme and rosemary (plus a sprig or two)",
            "2 small skinless chicken breasts",
            "150ml low-sodium chicken stock",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. Toss potatoes with oil, carrots, courgette, leek, herbs, and seasoning in a small roasting tray.",
            "Roast 30 minutes until starting to brown; stir veg, nestle chicken in, and roast 15 minutes more.",
            "Pour over stock and cook 5 minutes more until chicken and veg are cooked through.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 4,
        "name": "Roasted cauliflower & chicken curry",
        "tagline": "Roasted veg, rich curry sauce.",
        "time_prep_min": 20,
        "time_cook_min": 40,
        "time_total_min": 60,
        "link": "https://www.bbcgoodfood.com/recipes/roasted-cauliflower-chicken-curry",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "2 tbsp veg oil",
            "1 red onion (sliced)",
            "4 boneless skinless chicken thighs (chopped)",
            "3 garlic cloves (crushed/grated)",
            "thumb ginger (grated)",
            "2 tsp garam masala",
            "1 tsp ground cumin",
            "1 tsp turmeric",
            "1–2 tsp chilli powder",
            "1 tbsp tomato puree",
            "1 tbsp soy sauce",
            "400g chopped tomatoes",
            "400g coconut milk",
            "handful chopped coriander",
            "1 cauliflower (florets + sliced leaves + chopped core)",
            "2 tbsp veg oil",
            "1/2 tsp ground cumin",
            "1/2 tsp ground coriander",
            "1/2 tsp turmeric",
            "rice/naan/poppadums + lime wedges to serve",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. Toss cauliflower with oil and spices; roast 30–40 minutes until tender and charring at edges.",
            "In a large pan on medium-low, heat oil and fry onion, sliced leaves, and chopped core 8–10 minutes until softened.",
            "Add chicken, increase heat to medium, and fry 4–5 minutes until starting to brown. Add garlic and ginger; cook a couple minutes.",
            "Add spices; cook 1 minute. Stir in tomato puree and soy sauce, then tomatoes with a splash of water, then coconut milk.",
            "Simmer 15–20 minutes until chicken is cooked and sauce thickened. Serve with roasted cauliflower, coriander, and lime.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 5,
        "name": "Butternut squash & sage risotto",
        "tagline": "Creamy rice, sweet squash, crisp sage.",
        "time_prep_min": 10,
        "time_cook_min": 40,
        "time_total_min": 50,
        "link": "https://www.bbcgoodfood.com/recipes/butternut-squash-sage-risotto",
        "tags": ["SAUCY", "PANTRY"],
        "ingredients": [
            "1kg butternut squash (peeled, bite-size chunks)",
            "3 tbsp olive oil",
            "bunch sage (leaves picked; half chopped, half whole)",
            "1 1/2l veg stock",
            "50g butter",
            "1 onion (finely chopped)",
            "300g risotto rice (arborio)",
            "1 small glass white wine",
            "50g parmesan (or veg alternative), finely grated",
        ],
        "steps": [
            "Heat oven to 220C/200C fan/gas 7. Toss squash with 1 tbsp oil and chopped sage; roast 30 minutes until brown and soft.",
            "Bring stock to the boil, then keep at a low simmer. In another pan, melt half the butter and cook onion 8–10 minutes until soft.",
            "Add rice and stir until coated and glossy. Add wine and simmer until evaporated.",
            "Add stock a ladle at a time, stirring on low heat 25–30 minutes until creamy and al dente.",
            "Fry whole sage leaves in a little oil until crisp; drain on kitchen paper.",
            "Mash half the squash into a rough puree, keeping half in chunks.",
            "Stir in squash puree, parmesan, and remaining butter; rest a few minutes. Serve topped with squash chunks and crisp sage.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 6,
        "name": "Leek, ricotta & gruyere tart",
        "tagline": "Buttery tart, sweet leeks, proper dinner-party energy.",
        "time_prep_min": 25,
        "time_cook_min": 45,
        "time_total_min": 70,
        "link": "https://www.bbcgoodfood.com/recipes/leek-ricotta-gruyere-tart",
        "tags": ["VEGETARIAN", "PANTRY"],
        "ingredients": [
            "500g pack all-butter shortcrust pastry",
            "knob of butter",
            "2 large leeks, sliced",
            "250g ricotta",
            "100ml double cream",
            "2 eggs",
            "2 tbsp chopped tarragon",
            "100g gruyere (or vegetarian alternative), grated",
        ],
        "steps": [
            "Heat oven to 200C/180C fan/gas 6. Roll out pastry and line a 23cm loose-bottomed tart tin. Prick base. Line with parchment and baking beans and bake 10 minutes.",
            "Remove beans and parchment, bake another 5 minutes until pale golden. Reduce oven to 180C/160C fan/gas 4.",
            "Melt butter in a large pan. Cook leeks gently 10 minutes until softened.",
            "Beat ricotta, cream, eggs, and tarragon with a little salt and plenty of black pepper. Stir in leeks and all but a handful of the cheese.",
            "Pour into tart case, scatter remaining cheese on top. Bake 25–30 minutes until golden and set.",
            "Leave to settle 5 minutes, then remove from the tin and cool slightly on a rack. Serve warm.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 7,
        "name": "Creamy mustard & tarragon chicken",
        "tagline": "Quick, creamy, and herby.",
        "time_prep_min": 10,
        "time_cook_min": 25,
        "time_total_min": 35,
        "link": "https://www.bbcgoodfood.com/recipes/creamy-mustard-tarragon-chicken",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "1 tbsp sunflower oil",
            "4 boneless, skinless chicken breasts",
            "200ml tub half-fat creme fraiche",
            "1/2 tbsp each Dijon and wholegrain mustard",
            "1/4 tbsp dried tarragon (or 2 sprigs fresh)",
        ],
        "steps": [
            "Heat oven to 200C/fan 180C/gas 6. Heat oil in an ovenproof pan.",
            "Season chicken. Brown 1 minute per side in the pan, then remove to a plate.",
            "Add creme fraiche, both mustards, and tarragon to the pan; stir to combine and bring to a simmer.",
            "Return chicken to the pan and spoon sauce over.",
            "Bake 20 minutes until chicken is cooked through and sauce is bubbling.",
        ],
    },
    {
        "category_id": 5,
        "sort_order": 8,
        "name": "Roasted cauliflower cheese filo pie",
        "tagline": "Golden filo, rich cheese sauce.",
        "time_prep_min": 30,
        "time_cook_min": 80,
        "time_total_min": 110,
        "link": "https://www.bbcgoodfood.com/recipes/roasted-cauliflower-cheese-filo-pie",
        "tags": ["VEGETARIAN", "SAUCY"],
        "ingredients": [
            "1 head of cauliflower (leaves + stalk chopped small, then cut into florets)",
            "2 tbsp olive oil",
            "40g parmesan (or vegetarian Italian-style cheese)",
            "100g melted butter (or olive oil, for brushing pastry + tin)",
            "4 sheets filo pastry",
            "50g butter",
            "40g plain flour",
            "500ml whole milk",
            "1 tsp mustard powder (or English mustard)",
            "150g extra mature cheddar, grated",
            "grating of nutmeg",
            "pinch of cayenne pepper",
        ],
        "steps": [
            "Heat oven to 210C/190C fan/gas 7. Toss cauliflower with olive oil and a pinch of salt, grate over about a quarter of the parmesan, and roast 30 minutes until lightly charred. Set aside.",
            "Cheese sauce: melt 50g butter, stir in flour 2–3 minutes, then gradually whisk in milk. Cook 10 minutes until thickened. Stir in mustard powder and all but a handful of cheddar, then season with nutmeg and cayenne.",
            "Brush a round springform cake tin with butter/oil. Layer filo sheets, brushing each with butter/oil and scattering a little parmesan, overlapping to cover the base and sides.",
            "Tip roasted cauliflower into the centre, pour over cheese sauce, and ruffle the overhanging filo around the filling. Brush with more butter/oil and scatter remaining cheddar and parmesan.",
            "Bake 20 minutes, remove the tin ring (leave base), and bake 20 minutes more until crisp and golden. Cool slightly before serving.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 1,
        "name": "Luxe fish pie",
        "tagline": "Rich, glossy, and special.",
        "time_prep_min": 45,
        "time_cook_min": 70,
        "time_total_min": 115,
        "link": "https://www.bbcgoodfood.com/recipes/luxe-fish-pie",
        "tags": ["SEAFOOD", "SAUCY"],
        "ingredients": [
            "500g thick white fish fillets (e.g. cod/haddock), unskinned",
            "500g thick salmon fillet, unskinned",
            "300g smoked haddock (preferably undyed)",
            "700ml full-fat or semi-skimmed milk",
            "1 medium onion, thin wedges",
            "2 bay leaves",
            "75g butter",
            "75g plain flour",
            "140g young spinach leaves",
            "3 tbsp white wine or vermouth (optional)",
            "0.5 small pack dill, roughly chopped",
            "1.5kg potatoes",
            "50g butter",
            "100g mature cheddar (coarsely grated)",
            "300ml tub half-fat creme fraiche",
        ],
        "steps": [
            "Poach fish: put fish in a wide pan, pour over milk, add onion and bay. Bring to a very gentle simmer, cover and take off the heat immediately, then leave 10 minutes. Drain, reserving the infused milk.",
            "Mash: boil potatoes until soft, drain, and mash with butter, half the cheese, and creme fraiche; season.",
            "Sauce: melt butter, stir in flour, then gradually whisk in infused milk. Cook 3 minutes until thick. Stir in spinach and wine (optional) and cook 2 minutes. Off heat, stir in dill and season.",
            "Assemble: heat oven to 200C/180C fan/gas 6. Layer 1/3 sauce, 1/2 fish, 1/3 sauce, remaining fish, remaining sauce. Top with mash and remaining cheese.",
            "Bake 45 minutes until golden and bubbling.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 2,
        "name": "Easy mini beef wellingtons",
        "tagline": "Looks fancy, feels easy.",
        "time_prep_min": 15,
        "time_cook_min": 35,
        "time_total_min": 50,
        "link": "https://www.bbcgoodfood.com/recipes/easy-mini-beef-wellingtons",
        "tags": ["PROTEIN"],
        "ingredients": [
            "2 x 175g beef fillet steaks",
            "1 tsp olive oil",
            "320g puff pastry sheet",
            "100g roasted mushroom pate",
            "4 slices Parma ham",
            "1 egg (beaten)",
        ],
        "steps": [
            "Heat air fryer to its highest setting. Brush steaks with oil, season, and cook 4 minutes. Remove and cool completely. Rest pastry at room temp 10 minutes.",
            "Lay 2 Parma ham slices in a cross and put a steak in the centre. Repeat. Spoon pate on top, then fold ham over to make parcels.",
            "Cut pastry in half. Put each parcel at one end, brush pastry with a little water, fold over, and press to seal. Trim and crimp edges.",
            "Heat air fryer to 180C. Egg-wash and cook 15 minutes for medium or 20 minutes for well done. Rest a few minutes.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 3,
        "name": "Roast hake with caper-anchovy butter",
        "tagline": "Bright and bold.",
        "time_prep_min": 10,
        "time_cook_min": 30,
        "time_total_min": 40,
        "link": "https://www.theguardian.com/food/2025/nov/17/quick-easy-roast-hake-recipe-caper-anchovy-butter-georgina-hayden",
        "tags": ["SEAFOOD", "BRIGHT"],
        "ingredients": [
            "2 garlic cloves",
            "5 anchovies",
            "4 tbsp capers",
            "1/2 bunch chives",
            "1 lemon",
            "90g unsalted butter (cubes)",
            "salt + pepper",
            "250g sweetheart cabbage (or other greens)",
            "2 onions (halved)",
            "2 tbsp olive oil",
            "4 x 150g hake/cod fillets (skinned, pin-boned if needed)",
        ],
        "steps": [
            "Heat oven 220C (200C fan)/gas 7. Blitz garlic, anchovies, half the capers, most chives, lemon zest, butter, and seasoning to a paste.",
            "Shred cabbage and thinly slice onions. Toss with lemon juice, olive oil, and seasoning in a tray. Lay fish on top and spoon caper butter over fish and cabbage.",
            "Scatter remaining capers and lemon slices. Roast 16–20 minutes, basting halfway, until fish is tender and cabbage a bit charred. Finish with chopped chives.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 4,
        "name": "Spiced lamb pie",
        "tagline": "Deeply spiced and celebratory.",
        "time_prep_min": 30,
        "time_cook_min": 260,
        "time_total_min": 290,
        "link": "https://www.bbcgoodfood.com/recipes/spiced-lamb-pie",
        "tags": ["PROTEIN", "SWEET SALTY"],
        "ingredients": [
            "3 tbsp vegetable oil",
            "800g lamb shoulder (fat removed, diced)",
            "3 tbsp plain flour",
            "1 large onion (chopped)",
            "2 garlic cloves (crushed)",
            "1 tbsp ras el hanout",
            "2 tsp ground coriander",
            "2 tsp ground cumin",
            "good pinch ground cloves",
            "good pinch saffron (optional)",
            "1 cinnamon stick",
            "400g can chopped tomatoes",
            "1 lemon (zested/juiced)",
            "1 tbsp honey",
            "4 tbsp pomegranate molasses",
            "270g filo pastry (4–6 sheets)",
            "50g butter (melted)",
            "50g flaked almonds",
            "50g pomegranate seeds",
        ],
        "steps": [
            "Heat oil in a flameproof casserole. Toss lamb in flour and seasoning; brown in batches and set aside.",
            "Add onion and garlic; cook 5 minutes. Stir in spices, tomatoes, lemon zest/juice, honey, and molasses. Add water from the tomato can. Simmer, lid on, 2 1/2–3 hours until lamb is tender. Cool.",
            "Heat oven 180C/160C fan/gas 4. Put filling in a ~25cm pie dish. Brush filo with butter, scrunch and pile on top. Drizzle remaining butter and scatter almonds.",
            "Bake 45 minutes until crisp and golden; scatter pomegranate seeds just before serving.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 5,
        "name": "Slow cooker coq au vin",
        "tagline": "Slow-cooked, rich, and glossy.",
        "time_prep_min": 30,
        "time_cook_min": 240,
        "time_total_min": 270,
        "link": "https://www.bbcgoodfood.com/recipes/slow-cooker-coq-au-vin",
        "tags": ["PROTEIN", "SAUCY"],
        "ingredients": [
            "8 skin-on, bone-in chicken thighs",
            "30g butter",
            "140g smoked bacon lardons (or diced smoked pancetta)",
            "400g pearl onions or small shallots (peeled, left whole)",
            "2 large or 4 small carrots (chunks)",
            "2 garlic cloves (crushed)",
            "3 tbsp plain flour",
            "1 tbsp tomato puree",
            "300ml chicken stock",
            "600ml red wine",
            "2 bay leaves",
            "1 large thyme sprig",
            "300g button chestnut mushrooms (whole or chopped)",
            "handful parsley leaves (optional)",
            "mash or buttered tagliatelle (to serve)",
        ],
        "steps": [
            "Season chicken. Melt half the butter; cook chicken skin-side down 10 minutes until deep golden. Flip and seal, then transfer to slow cooker.",
            "Fry bacon 5–6 minutes until crisp; add to slow cooker. Fry onions and carrots 5 minutes; add garlic 1 minute.",
            "Stir in flour 1–2 minutes, then tomato puree 2 minutes. Bring to the boil, then simmer 2 minutes.",
            "Tip pan contents over chicken. Add stock and wine to the pan, bring to the boil, then pour into slow cooker. Add bay and thyme; cook high 3–4 hrs / medium 5–6 / low 7–8.",
            "Fry mushrooms in remaining butter 4–5 minutes; add to slow cooker about 1 hour before the end. Finish with parsley.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 6,
        "name": "Pan-fried salmon",
        "tagline": "Crisp skin, quick finish.",
        "time_prep_min": 1,
        "time_cook_min": 5,
        "time_total_min": 6,
        "link": "https://www.bbcgoodfood.com/recipes/pan-fried-salmon",
        "tags": ["SEAFOOD", "BRIGHT"],
        "ingredients": [
            "2 x 150g smoked salmon fillets (about 4cm thick), skin on",
            "1/2 tbsp olive oil",
            "20g unsalted butter",
            "1/2 lemon (juiced)",
        ],
        "steps": [
            "Season salmon well. Heat oil and butter in a non-stick pan on medium until melted and foaming, then turn heat up.",
            "Add salmon skin-side down and fry 3 minutes until crisp.",
            "Flip, lower heat, cook 2 minutes more, then drizzle lemon juice. Transfer to a plate and baste with pan juices.",
        ],
    },
    {
        "category_id": 6,
        "sort_order": 7,
        "name": "Slow-cooked shredded lamb shoulder",
        "tagline": "Big-feast energy, worth the wait.",
        "time_prep_min": 15,
        "time_cook_min": 240,
        "time_total_min": 480,
        "link": "https://www.theguardian.com/food/2024/dec/28/slow-cooked-shredded-lamb-shoulder-recipe-honey-and-co",
        "tags": ["PROTEIN", "SWEET SALTY"],
        "ingredients": [
            "1 whole lamb shoulder on the bone (~3kg)",
            "100g gochujang",
            "100g orange marmalade",
            "1 tbsp sea salt",
            "2 tbsp coriander seeds",
            "1 red pepper",
            "2 red chillies",
            "2 red onion (peeled/halved)",
            "1 orange (halved)",
            "1 tsp sugar",
            "1/2 tsp salt",
            "2 tbsp white-wine vinegar",
            "1 orange (peeled/segmented)",
            "1 clementine (peeled/sliced)",
            "2 red onions (thinly sliced)",
            "30g parsley leaves",
            "50g rocket",
            "2 tbsp white-wine vinegar",
            "2 tbsp olive oil",
            "1 tsp sumac",
            "1/2 tsp sea salt",
        ],
        "steps": [
            "Score deep crisscross cuts in lamb. Mix gochujang, marmalade, salt, and coriander seeds; rub all over. Cover and chill at least 4 hours.",
            "Heat oven 240C (220C fan)/gas 9. Put lamb in a deep tray with pepper, chillies, onions, and orange to one side. Roast 30 minutes; remove scorched veg; cover lamb and roast 30 minutes more.",
            "Lower to 220C (200C fan)/gas 7, add 500ml water, baste, cover; roast 30 minutes.",
            "Lower to 200C (180C fan)/gas 6: baste, cover, cook 1 hour. Lower to 180C (160C fan)/gas 4: baste, cover, cook final 1 hour.",
            "Relish: chop roasted veg and orange; simmer with sugar, salt, vinegar, and 120ml water for 10 minutes until thick.",
            "Salad: combine fruit, onions, parsley, and rocket. Whisk dressing and toss before serving.",
            "Shred lamb in the tray, mixing into juices. Serve with relish and salad.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 1,
        "name": "Fish fingers & mushy peas",
        "tagline": "Crisp fish, minty peas.",
        "time_prep_min": 15,
        "time_cook_min": 10,
        "time_total_min": 25,
        "link": "https://www.bbcgoodfood.com/recipes/fish-fingers-mushy-peas",
        "tags": ["SEAFOOD", "GREENS"],
        "ingredients": [
            "600g firm skinless white fish (pollock/hake)",
            "50g plain flour (seasoned)",
            "1 large egg (lightly whisked)",
            "200g fine fresh breadcrumbs",
            "2 tbsp vegetable oil",
            "400g frozen peas",
            "knob of butter",
            "zest 1 lemon (plus wedges to serve)",
            "small handful mint (finely shredded)",
            "new potatoes to serve (optional)",
        ],
        "steps": [
            "Slice fish into 12 fingers. Set up bowls of flour, egg, and breadcrumbs. Coat fish flour → egg → crumbs and chill 15 minutes.",
            "Heat oil in a large frying pan. Fry fish fingers about 8 minutes, turning occasionally, until golden and cooked.",
            "Boil peas 4 minutes until very tender, drain, then mash with butter, lemon zest, and mint. Season.",
            "Serve fish with mushy peas, lemon wedges, and optional new potatoes.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 2,
        "name": "Chicken goujons",
        "tagline": "Crispy strips with easy sides.",
        "time_prep_min": 15,
        "time_cook_min": 15,
        "time_total_min": 30,
        "link": "https://www.bbcgoodfood.com/recipes/crispy-chicken-strips",
        "tags": ["PROTEIN", "PANTRY"],
        "ingredients": [
            "150ml buttermilk (or skimmed milk + 2 tsp lemon juice, stand 5 mins)",
            "2 large chicken breasts",
            "50g panko breadcrumbs",
            "1 tbsp rapeseed oil",
            "2 tbsp ketchup",
            "1 tsp soy sauce",
            "1/2 tsp white wine vinegar",
            "2 large carrots (~300g), grated",
            "1/2 lemon (juiced)",
            "1 tbsp olive oil",
            "baked potatoes (to serve)",
        ],
        "steps": [
            "Coat sliced chicken in buttermilk and chill 1 hour.",
            "Toast breadcrumbs in a dry pan 2–3 minutes until pale brown.",
            "Heat oven to 230C/210C fan/gas 8. Coat chicken in crumbs.",
            "Fry chicken in a little oil 1–2 minutes each side, then bake 5 minutes. Rest 5 minutes and slice.",
            "Mix sauce ingredients. Make carrot salad with lemon and olive oil. Serve with baked potatoes.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 3,
        "name": "Veggie burgers + slaw",
        "tagline": "Zero-brain burgers and slaw.",
        "time_prep_min": 10,
        "time_cook_min": 10,
        "time_total_min": 20,
        "link": "https://groceries.morrisons.com/recipes/veggie-burger-and-slaw/94609",
        "tags": ["VEGETARIAN"],
        "ingredients": [
            "190g cabbage (shredded)",
            "4 veggie burgers",
            "1 carrot (~90g)",
            "150g natural yoghurt (or mayo)",
            "1 onion (~80g)",
            "1 apple grated (~80g)",
            "50g cucumber",
            "85g tomato",
            "80g little gem lettuce",
            "4 cheese slices (optional)",
        ],
        "steps": [
            "Make slaw: slice cabbage and onion, grate apple and carrot, and mix with yoghurt (or mayo).",
            "Cook veggie burgers to packet instructions.",
            "Build burgers with lettuce, tomato, cucumber, cheese (optional), and slaw.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 4,
        "name": "Salmon traybake",
        "tagline": "Roast salmon with greens.",
        "time_prep_min": 10,
        "time_cook_min": 40,
        "time_total_min": 50,
        "link": "https://www.bhf.org.uk/informationsupport/support/healthy-living/healthy-eating/recipe-finder/salmon-traybake",
        "tags": ["SEAFOOD", "GREENS", "BRIGHT"],
        "ingredients": [
            "new potatoes",
            "broccoli or asparagus",
            "olive oil",
            "garlic",
            "thyme",
            "parsley",
            "mint",
            "lemon",
            "salmon fillets",
            "tomatoes",
        ],
        "steps": [
            "Boil new potatoes 5 minutes; add broccoli/asparagus and cook 2 minutes more; drain and set greens aside.",
            "Toss potatoes with olive oil, garlic, and thyme. Roast at 200C/180C fan/gas 6 about 20 minutes.",
            "Mix parsley and mint with lemon juice and zest; pat onto salmon.",
            "Add greens among potatoes; put salmon fillets and tomatoes on top. Roast 10–12 minutes until salmon flakes easily.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 5,
        "name": "Cowboy pie",
        "tagline": "Sausage, beans, mash top.",
        "time_prep_min": 20,
        "time_cook_min": 60,
        "time_total_min": 80,
        "link": "https://www.bbcgoodfood.com/recipes/cowboy-pie",
        "tags": ["PROTEIN", "PANTRY"],
        "ingredients": [
            "2 tsp sunflower oil",
            "1 onion, finely chopped",
            "8 pork sausages, cut into bitesize pieces",
            "2 garlic cloves, crushed/fine grated",
            "2 tsp hot smoked paprika",
            "2 x 410g cans baked beans",
            "3 tbsp barbecue sauce",
            "1kg potatoes (peeled, roughly chopped)",
            "50g butter",
            "4 tbsp milk",
            "75g grated cheddar",
            "chives to garnish (optional)",
        ],
        "steps": [],
    },
    {
        "category_id": 8,
        "sort_order": 6,
        "name": "Teriyaki gyoza stir-fry",
        "tagline": "Fast veg + gyoza.",
        "time_prep_min": 5,
        "time_cook_min": 20,
        "time_total_min": 25,
        "link": "https://www.itsu.com/grocery/recipes/teriyaki-gyoza-stir-fry/",
        "tags": ["PROTEIN", "GREENS", "SAUCY"],
        "ingredients": [
            "6 itsu teriyaki chick'n vegan gyoza",
            "300g cooked noodles",
            "1 tsp olive oil",
            "1 cup chopped broccoli",
            "1 cup chopped mushrooms",
            "1 cup baby corn",
            "1 cup chopped peppers",
            "400ml teriyaki stir-fry sauce",
            "1 spring onion (finely sliced)",
            "2 handfuls spinach",
            "2 pinches sesame seeds",
        ],
        "steps": [
            "Cook veg with stir-fry sauce in a pan until softened and starting to brown.",
            "Cook noodles and steam gyoza to pack instructions.",
            "Split noodles into bowls, top with veg, gyoza, spring onion, sesame, and spinach on the side.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 7,
        "name": "Halloumi salad with couscous",
        "tagline": "Quick halloumi, fresh salad.",
        "time_prep_min": 10,
        "time_cook_min": 15,
        "time_total_min": 25,
        "link": "https://www.walderwellness.com/easy-halloumi-salad-with-couscous/",
        "tags": ["VEGETARIAN", "GREENS"],
        "ingredients": [
            "1/3 cup pearl/Israeli couscous (dry) (or 1 cup cooked)",
            "1 block halloumi",
            "4 cups arugula",
            "1 cup cucumber (sliced)",
            "1 cup cherry/grape tomatoes (halved)",
            "1 cup strawberries (quartered)",
            "1 cup steamed baby beets (quartered)",
            "1/4 cup fresh mint (chopped)",
            "1 avocado (chunks)",
            "1/4 cup olive oil",
            "2 tbsp balsamic vinegar",
            "1/2 lemon",
            "1 tsp honey",
            "1 tsp garlic powder",
            "salt + pepper",
        ],
        "steps": [
            "Cook couscous to package directions.",
            "Chop veg/fruit and add to a bowl with arugula.",
            "Whisk dressing ingredients.",
            "Cook halloumi slices 1–2 minutes per side until browned.",
            "Toss couscous and salad with dressing; top with halloumi and season.",
        ],
    },
    {
        "category_id": 8,
        "sort_order": 8,
        "name": "Cheats pizza + rocket salad",
        "tagline": "Flatbread pizza + balsamic rocket.",
        "time_prep_min": 15,
        "time_cook_min": 15,
        "time_total_min": 30,
        "link": "https://www.vegkit.com/recipes/vegan-main-meals/freshly-picked-vegan-cheese-cheats-pizza-rocket-salad/",
        "tags": ["VEGETARIAN", "GREENS"],
        "ingredients": [
            "1 pack flatbreads",
            "200g tomato paste (or dairy-free pesto or hummus)",
            "1 onion (sliced)",
            "1 capsicum (sliced)",
            "1 punnet cherry tomatoes",
            "100g Kalamata olives (pitted)",
            "100g sun-dried tomatoes",
            "200g sweet potato or pumpkin (roasted)",
            "1 packet plant-based cheese",
            "30ml balsamic vinegar",
            "1/2 tsp dried oregano",
            "1/2 tsp thyme (dried or fresh)",
            "fresh basil leaves",
            "salt & pepper",
            "1 packet rocket",
            "1/2 red onion thinly sliced",
            "fresh herbs",
            "extra virgin olive oil",
        ],
        "steps": [
            "Heat oven to 190C. Preheat trays lined with baking paper.",
            "Spread base sauce on flatbreads, add toppings, drizzle oil, and season.",
            "Bake about 15 minutes until edges are crisp and toppings are lightly charred.",
            "Toss salad ingredients with olive oil and balsamic; season and serve alongside pizza.",
        ],
    },
]

def _rows_to_insert(rows: Iterable[dict]) -> list[tuple]:
    now = datetime.utcnow().isoformat()
    items: list[tuple] = []
    for row in rows:
        items.append(
            (
                row["category_id"],
                row.get("sort_order", 0),
                row["name"],
                row.get("tagline"),
                row.get("time_prep_min"),
                row.get("time_cook_min"),
                row.get("time_total_min"),
                row.get("link"),
                row.get("image_url"),
                json.dumps(row.get("tags") or []),
                json.dumps(row.get("ingredients") or []),
                json.dumps(row.get("steps") or []),
                now,
            )
        )
    return items

def seed_foodhub(conn: sqlite3.Connection) -> None:
    cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='foodhub';")
    if cursor.fetchone() is None:
        return
    existing = conn.execute("SELECT COUNT(1) AS count FROM foodhub;").fetchone()
    if existing and existing["count"] > 0:
        conn.execute(
            """
            DELETE FROM foodhub
            WHERE (category_id = 5 AND name IN ('Cheeseburger & chips', 'Chilli con carne', 'Classic lasagne'))
               OR (category_id = 6 AND name = 'Mushroom stroganoff');
            """
        )
        for row in FOODHUB_SEED:
            found = conn.execute(
                "SELECT id FROM foodhub WHERE name = ? AND category_id = ?;",
                (row["name"], row["category_id"]),
            ).fetchone()
            payload = (
                row.get("sort_order", 0),
                row.get("tagline"),
                row.get("time_prep_min"),
                row.get("time_cook_min"),
                row.get("time_total_min"),
                row.get("link"),
                row.get("image_url"),
                json.dumps(row.get("tags") or []),
                json.dumps(row.get("ingredients") or []),
                json.dumps(row.get("steps") or []),
                row["name"],
                row["category_id"],
            )
            if found:
                conn.execute(
                    """
                    UPDATE foodhub
                    SET
                      sort_order = ?,
                      tagline = ?,
                      time_prep_min = ?,
                      time_cook_min = ?,
                      time_total_min = ?,
                      link = ?,
                      image_url = ?,
                      tags = ?,
                      ingredients = ?,
                      steps = ?
                    WHERE name = ? AND category_id = ?;
                    """,
                    payload,
                )
            else:
                now = datetime.utcnow().isoformat()
                conn.execute(
                    """
                    INSERT INTO foodhub (
                      category_id,
                      sort_order,
                      name,
                      tagline,
                      time_prep_min,
                      time_cook_min,
                      time_total_min,
                      link,
                      image_url,
                      tags,
                      ingredients,
                      steps,
                      created_at
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
                    """,
                    (
                        row["category_id"],
                        row.get("sort_order", 0),
                        row["name"],
                        row.get("tagline"),
                        row.get("time_prep_min"),
                        row.get("time_cook_min"),
                        row.get("time_total_min"),
                        row.get("link"),
                        row.get("image_url"),
                        json.dumps(row.get("tags") or []),
                        json.dumps(row.get("ingredients") or []),
                        json.dumps(row.get("steps") or []),
                        now,
                    ),
                )
        return
    rows = _rows_to_insert(FOODHUB_SEED)
    conn.executemany(
        """
        INSERT INTO foodhub (
          category_id,
          sort_order,
          name,
          tagline,
          time_prep_min,
          time_cook_min,
          time_total_min,
          link,
          image_url,
          tags,
          ingredients,
          steps,
          created_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
        """,
        rows,
    )
